version: "3.7"

services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - homebridge_data:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - ENABLE_AVAHI=0
      - TZ=Europe/Warsaw
    logging:
      driver: json-file
      options:
        max-size: "10mb"

volumes:
  homebridge_data: