version: "3.9"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      # Strefa cz
      TZ: Europe/Warsaw
      
      # Lista kontenerów do aktualizacji (oddzielone spacją)
      WATCHTOWER_CONTAINERS: "homeassistant homebridge portainer"

      # Interwał sprawdzania aktualizacji (w sekundach) — np. co 6 godzin
      WATCHTOWER_SCHEDULE: "0 0 1 * * *"

      # Ustawienia powiadomień e-mail
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "<mail_from_address>"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "<mail"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "<server>"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 465
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "<server"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "<password>"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2

      # Opcjonalnie — czy restartować kontenery po aktualizacji
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"

    labels:
      - com.centurylinklabs.watchtower.enable=true

    command:
      --cleanup
      --include-restarting